apiVersion: v1
kind: Secret
metadata:
  name: {{ template "keycloak-gatekeeper.fullname" . }}
  labels:
    app: {{ template "keycloak-gatekeeper.name" . }}
    chart: {{ template "keycloak-gatekeeper.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  clientSecret: {{ .Values.clientSecret | b64enc | quote }}
{{- if .Values.encryptionKey }}
  encryptionKey: {{ .Values.proxy.encryptionKey | b64enc | quote }}
{{- else  }}
  encryptionKey: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}